[build]
default-target = "aarch64-unknown-linux-gnu"    # use this target if none is explicitly provided
pre-build = [                                  # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update && apt-get --assume-yes install binutils:$CROSS_DEB_ARCH libomp-10-dev:$CROSS_DEB_ARCH clang-10:$CROSS_DEB_ARCH clang:$CROSS_DEB_ARCH llvm-dev:$CROSS_DEB_ARCH libclang-dev:$CROSS_DEB_ARCH"
]                 
